<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <WarningsAsErrors>$(WarningsAsErrors);CS1591</WarningsAsErrors>
    <Version>0.3.0-preview.1</Version>
    <Authors>hez2010</Authors>
    <Description>A Language Server Protocol client for CodeEdit.Maui and .NET applications.</Description>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/hez2010/RichEdit.Maui</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>lsp;language-server;client</PackageTags>
  </PropertyGroup>
  <ItemGroup>
    <None Include="../LICENSE.txt" Pack="true" PackagePath="LICENSE.txt" />
    <None Include="README.md" Pack="true" PackagePath="README.md" />
    <InternalsVisibleTo Include="RichEdit.Maui.Tests" />
  </ItemGroup>
</Project>
